import { describe, it, expect } from "vitest";
import { buildCompanionMarkdown } from "../src/hooks/useComments";
import type { CommentsFile } from "../src/types/comments";

describe("Companion File Generator", () => {
  it("generates companion markdown matching spec template", () => {
    const mdContent = `# My Document

The strategy <mark>should focus on long-term growth</mark><sup>[c1]</sup> rather than
<mark>quick wins</mark><sup>[c2]</sup> that don't compound.`;

    const commentsFile: CommentsFile = {
      version: 1,
      comments: {
        c1: {
          thread: [
            {
              id: "m_abc1",
              author: "Dave",
              timestamp: "2026-02-13T10:30:00Z",
              body: 'Should we rephrase this? "Long-term growth" is vague.',
            },
            {
              id: "m_abc2",
              author: "Sarah",
              timestamp: "2026-02-13T10:35:00Z",
              body: 'How about "sustainable revenue growth"?',
            },
          ],
          resolved: true,
          resolvedBy: "Dave",
          resolvedAt: "2026-02-13T10:42:00Z",
          createdAt: "2026-02-13T10:30:00Z",
        },
        c2: {
          thread: [
            {
              id: "m_abc3",
              author: "Dave",
              timestamp: "2026-02-13T11:00:00Z",
              body: "Do we need this contrast? Feels slightly passive-aggressive.",
            },
          ],
          resolved: false,
          createdAt: "2026-02-13T11:00:00Z",
        },
      },
    };

    const output = buildCompanionMarkdown(
      "/path/to/my-document.md",
      mdContent,
      commentsFile,
    );

    // Check structure
    expect(output).toContain("# Comments — my-document.md");
    expect(output).toContain(
      "*Generated by Gutter. Do not edit — regenerated on save.*",
    );

    // Check c1 thread
    expect(output).toContain('[c1]** on "should focus on long-term growth"');
    expect(output).toContain("Dave");
    expect(output).toContain("Sarah");
    expect(output).toContain("Resolved by Dave");

    // Check c2 thread
    expect(output).toContain('[c2]** on "quick wins"');
    expect(output).toContain("passive-aggressive");
    expect(output).toContain("Open");

    // Check footer
    expect(output).toContain("2 comments (1 resolved, 1 open)");
  });

  it("handles no comments", () => {
    const commentsFile: CommentsFile = {
      version: 1,
      comments: {},
    };

    const output = buildCompanionMarkdown(
      "/path/to/doc.md",
      "# Hello",
      commentsFile,
    );

    expect(output).toContain("# Comments — doc.md");
    expect(output).toContain("0 comments (0 resolved, 0 open)");
  });

  it("truncates long anchor text to 80 chars", () => {
    const longText = "a".repeat(100);
    const mdContent = `<mark>${longText}</mark><sup>[c1]</sup>`;

    const commentsFile: CommentsFile = {
      version: 1,
      comments: {
        c1: {
          thread: [
            {
              id: "m_abc",
              author: "Dave",
              timestamp: "2026-02-13T10:00:00Z",
              body: "Too long",
            },
          ],
          resolved: false,
          createdAt: "2026-02-13T10:00:00Z",
        },
      },
    };

    const output = buildCompanionMarkdown("/path/doc.md", mdContent, commentsFile);
    expect(output).toContain("a".repeat(80) + "...");
  });
});
